# Generated by Django 3.2.9 on 2021-11-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('repo', models.CharField(max_length=255, unique=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.activity')),
            ],
        ),
    ]
