# Generated by Django 3.2.9 on 2021-11-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
